.github/workflows/release.yml, CONTRIBUTING.md
The previous action used for computing the next version was actually not using conventional commit messages to compute the version. I found a new action that can do that for us instead.
=> chore: update release process

sarif_types.go, scan.go, scan_test.go
We have agreed with Analysis and the CLI on what the Analysis API will return.
This PR updates the existing fake SARIF response for scanning to include ignores for one of the results, so that we can do development in the IDEs.
Ticket: https://snyksec.atlassian.net/browse/IDE-176
Tested it with https://github.com/snyk/snyk-ls/pull/464 and https://github.com/snyk/snyk-intellij-plugin/pull/490 and without those changes, to make sure it's still backwards compatible.
=> feat: fake ignore findings [IDE-176]

.circleci/config.yml, .gitleaksignore, internal/analysis/analysis_test.go, internal/analysis/fake.json
Adds code quality issues to the mock data returned by `code-client-go`.
Tested in VSCode with https://github.com/snyk/vscode-extension/pull/449 <img width="419" alt="Screenshot 2024-04-02 at 15 16 27" src="https://github.com/snyk/code-client-go/assets/81559517/a281872d-d9fe-4120-a639-3a69c5d70b84">
I will use it to test https://github.com/snyk/snyk-intellij-plugin/pull/496 more comprehensively.
=> fix: include code quality issues

internal/bundle/bundle_manager.go, internal/deepcode/helpers.go, scan_test.go
replaced the usage of the global logger by an instance of a parameterized logger.
=> fix: remove usage of global logger

internal/util/repository.go, internal/util/repository_test.go
The Workspace API expects a proper URL so I've used a replace to generate the HTTPS URL from the SSH one. I don't know if this is resilient but I don't see why it wouldn't work. 
https://app.datadoghq.com/logs?query=%40service%3Aworkspace-service%20%40requestId%3A17f55c01-aca3-433f-aa3c-fa324908799a%20&agg_m=%40envoy.response_code&agg_q=status%2Cservice&agg_t=avg&analyticsOptions=%5B%22line%22%2C%22dog_classic%22%2Cnull%2Cnull%5D&cols=host%2Cservice%2C%40envoy.response_code&event=AgAAAY7DXoQSlnVN2gAAAAAAAAAYAAAAAEFZN0RYdDliQUFBR0NVSDlPOWtYUVFIdQAAACQAAAAAMDE4ZWMzNWYtODE3ZC00MjMxLTkzNmUtNWFkZmI0NWRiMjM5&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort_m=%2C&sort_t=%2C&storage=hot&stream_sort=%40envoy.response_code%2Casc&top_n=10%2C10&top_o=top%2Ctop&viz=stream&x_missi …
=> fix: repository url computation

sarif/sarif_types.go
Switch to using a named struct for the Sarif field so that we can reuse it in other places.
=> fix: extract sarif document to named Struct for reuse

http/http.go, http/http_test.go, internal/analysis/analysis_test.go, internal/deepcode/client_pact_test.go, internal/util/repository.go, internal/util/repository_test.go, internal/workspace/2024-03-12/client_pact_test.go, observability/error_reporter_impl.go, observability/instrumentor_impl.go, observability/noop_span.go, observability/traceid.go, scan_smoke_test.go
The CLI team have requested to be able to make the retry count configurable in the HTTP client.
The computation logic for the repo URL should work even on sub-folders.
=> fix: repo url subfolder [IDE-246]

http/http.go, internal/analysis/analysis.go, internal/analysis/analysis_test.go
Improve the logging so it's easier to debug and adds some error handling tests that verify that our error handling works when calling the workspace API. 
Also removes the `bundleHash` from logs since it's considered sensitive info.
=> refactor: logging improvements [IDE-254]

README.md, http/http.go, internal/analysis/analysis.go, internal/analysis/analysis_test.go, internal/bundle/bundle.go, internal/bundle/bundle_manager.go, internal/bundle/bundle_manager_test.go, internal/bundle/bundle_test.go, internal/deepcode/client.go, internal/deepcode/client_pact_test.go, internal/deepcode/client_test.go, internal/deepcode/mocks/client.go, scan.go, scan_smoke_test.go, scan_test.go
Refactors the external functions exposed by this library to use the function options pattern.
Left out the `config` and `httpClient` from the function options pattern for the scanner because there isn't a logical fallback for them. Also left out the `httpClientFactory` for the same reason.
=> refactor: use the function options pattern for external functions

http/http.go, http/http_test.go, internal/analysis/analysis_test.go
Forgot to re-init the error reporter logger with the provided logger and while I was looking at the http client I wanted to refactor the logic a bit so it's easier to follow.
=> refactor: http logger option

internal/analysis/analysis.go, internal/analysis/analysis_test.go, internal/analysis/mocks/analysis.go, scan.go, scan_smoke_test.go, scan_test.go, scripts/utils.py
This commit integrates the new Analysis API in Snyk Code scanning flow.
It does poll for result, but does not actually reads out the findings.
=> Added the call for RunAnalysis to Trigger Analysis API

internal/analysis/analysis.go, internal/analysis/analysis_test.go, internal/orchestration/2024-02-16/client_pact_test.go, internal/orchestration/2024-02-16/pacts/code-client-go-orchestrationapi.json, internal/workspace/2024-03-12/client_pact_test.go, internal/workspace/2024-03-12/pacts/code-client-go-workspaceapi.json
Added the call to retrieve the findings from the findings URL. Also added a simple Pact contract test for the Analysis APIs and improved the unit tests a bit so that the mocks verify the URL being called, which helps differentiate between mocks and makes sure we don't use the response from a different mock.
Tested using smoke tests.
=> feat: retrieve real findings [IDE-245]

.gitleaksignore, internal/analysis/analysis.go, internal/analysis/analysis_test.go, internal/analysis/fake.json, sarif/sarif_types.go, scan_smoke_test.go
The response from the backend has changed a bit so I updated the JSON fields in the type to match the response. Thankfully this doesn't affect anything downstream, since the type is used directly.
I've tested it with and without the feature flag in IntelliJ, since this `SarifResponse` type is used by old flow too.
Now we can test with any repo (still only in dev), not just `target-service`. The only thing is that we are not receiving ignores yet because the Ignores SDK is not ready.
With FF:
Without FF:
=> fix: deal with real sarif response

internal/analysis/analysis.go
We don't want to log the findings URL so updating the code to remove that and to also improve the logging a bit.
=> fix: logging for retrieving SARIF

scan/target.go, scan/target_test.go
Handle scenario when target does not have a defined repository URL
=> fix: fall back to path when no repo URL provided

internal/util/repository_test.go, internal/util/testutil/clone.go, scan_smoke_test.go
Since https://github.com/snyk/code-client-go/pull/34/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34, the newly added unit tests are failing in the GitHub action because an SSH agent is not configured for `go-git` to do a clone of the repos. We might need to configure an SSH agent but I found it weird since we clone in `snyk-ls` and we don't have one configured there (or a PAT configured for this step specifically). What we do there is use the `SetupCustomTestRepo` instead of `go-git` to clone inside the tests. So I've opened this PR to refactor the code to not use `go-git` to clone the repo in the hopes it fixes the problem and also because it makes the code more consistent.
=> test: fix git clone tests

internal/util/repository_test.go
The fix in https://github.com/snyk/code-client-go/commit/1d45bef77b74550a761eca400fd6e634d0be1614 worked but there's still one failing test and it's the one doing an ssh clone. We don't need to do that to reproduce the test case we need, so this changes the code to do a HTTPS clone but still test for the edge case.
=> test: fix git clone tests for ssh

sarif/sarif_types.go
Refactor to introduce `SarifCoverage` type and expose for reuse in downstream clients. 
=> fix: expose SarifCoverage as reusable type

internal/analysis/analysis.go
Currently IntelliJ adds a /v1 suffix for the API URL. This is a temp workaround until the new cli stable is released.
=> fix: remove v1 suffix for ApiUrl if exists [IDE-353]

internal/analysis/analysis_test.go
This fixes a failing unit test caused by a mis-match in mocked API version.
=> fix: mocked api version in not-a-repo unit test

internal/util/repository.go, internal/util/repository_test.go, scan_smoke_test.go
Like the ticket says, the backend has been able to deal with SSH repos for a while now. So removing this hack.
https://snyksec.atlassian.net/browse/IDE-257
Tested and it still works for SSH repos. 
**Question**: Should I remove the smoke test that shows that this works, since it's the backend's responsibility to make sure SSH and HTTPS repos both work?
=> refactor: remove redundant ssh transformation [IDE-257]

internal/analysis/analysis.go, internal/bundle/bundle.go, internal/bundle/bundle_manager_test.go, internal/bundle/mocks/bundle.go, internal/workspace/2024-05-14/client.go, scan.go, scan_test.go
As seen in the ticket, when changing a file we would return 0 vulnerabilities. This was because all vulnerabilities came from the same file and the incremental scanning mode was using absolute path instead of relative path to send the `limitToFiles`. To fix this, this PRs uses the computed `limitToFiles` for the bundle, which contain the relative path.
Also added the value to the debug log and configured the logger in the `analysisOrchestrator` to be injected using the function options pattern.
=> fix: send the correct limitToFiles to the incremental scan [IDE-402]

README.md, config/config.go, config/mocks/config.go, internal/analysis/analysis.go, internal/analysis/analysis_test.go, internal/util/testutil/test_config.go, internal/workspace/2024-05-14/client.go
In `snyk-ls` we have a way to override the timeout and it's set to 12h by default. This PR removes the local 2minutes timeout and the option to override the timeout and instead uses the config to decide how long to wait.
The CLI will also need to configure this.
=> feat: read snyk code timeout from config [IDE-399]

.github/CODEOWNERS
We want to make sure the provider has visibility of changes to the Pact contract so that if we accidentally use the API incorrectly (but the API validation somehow allows it) we don’t introduce an edge case silently. This way the owners of the provider are notified of changes to the Pact contract which is being tested against in https://github.com/snyk/workspace-service/pull/1065.
=> chore: add codeowner pact [IDE-296] 

sarif/sarif_types.go
Capitalizes the `region` field in the SARIF type definition. This should enable package consumers to construct SARIF payloads without encountering `region not exported by package sarif` errors.
=> feat: export sarif region field [TREX-1159]

internal/analysis/analysis_test.go, internal/analysis/fake.json, sarif/sarif_types.go
Currently the propertyBag property `Policy` is a mandatory field, which results in code-client-go returning and "empty" policy when it is not provided upstream. 
This PR omits the `Policy` when it is not provided.
This change results in the CLI not rendering the `Policy` details when none are available:
OLD
```
"properties": {
"priorityScore": 828,
"priorityScoreFactors": [
{
"label": true,
"type": "multipleOccurrence"
},
{
"label": true,
"type": "hotFileSource"
},
{
"label": true,
"type": "fixExamples"
}
],
"isAutofixable": false,
"snykPolicy/v1": {
"originalLevel": "",
"originalSeverity": "",
"severity": ""
}
}
```
NEW
```
"properties": {
"priorityScore": 828,
"priorityScoreFactors": [
{
"label": true,
"type": "multipleOccurrence"
},
{
"label": true,
"type": "hotFileSource"
},
{ …
```
=> fix: make ResultProperties.Policy nilable

http/http.go, llm/api_client.go, llm/api_client_test.go, llm/binding.go, llm/binding_smoke_test.go, llm/binding_test.go, llm/options.go, llm/types.go, observability/traceid.go
This provides an api client for the Explain API.
=> feat: new LLM binding

llm/api_client.go, llm/api_client_test.go, llm/types.go
The explain API doesn't expect a root-level object.
=> fix: AI explain request body

internal/analysis/analysis.go, internal/api/test/2024-12-21/helper.go
Accepts a `targetReference` for local tests which is then passed to the Test request.
=> feat: accept a target_reference value and pass it to the test request [OI-788]

internal/util/testutil/test_config.go, scan.go, scan_test.go
Extracted the Upload logic of the code scanner into its own exported function.
Improved error handling for code reuse and readability.
=> refactor: extract bundle upload logic [IDE-1085]

llm/api_client.go, llm/api_client_test.go
Send encoded code diffs in the request to the Explain API to resolve Firewall Issues.
=> fix: encode diffs sent to AI Explain API endpoint [IDE-1084]

internal/bundle/bundle.go, internal/bundle/bundle_manager.go, internal/bundle/bundle_manager_test.go, internal/bundle/mocks/bundle.go, internal/deepcode/helpers.go, internal/util/hash.go
Refactor bundle handling so that:
- We don't read files into memory by default
- We never read files into memory when the fiesize is too large to process
- We read files into memory at the point that they are uploaded as part of a bundle, and clear the memory immediately afterwards.
Tested on IntelliJ to ensure that CCI scanning behaviour is still the same.
=> feat: improve bundle performance [IDE-937]

llm/api_client.go, llm/api_client_test.go, llm/binding.go
_Provide description of this PR and changes, if linked Jira ticket doesn't cover it in full._
=> fix: set org header for AI Fix

http/http.go, internal/analysis/analysis.go, internal/analysis/analysis_legacy.go, internal/analysis/analysis_legacy_test.go, internal/analysis/mocks/analysis.go, internal/deepcode/client.go, llm/api_client.go, llm/api_client_test.go, scan.go, scan/tracker.go
Moved non-CCI bundle analysis from Language Server to Code Client Go, so Bundle and Upload logic is now shared.
- [n/a] README.md updated, if user-facing
=> refactor: move bundle analysis [IDE-1104]

Makefile, bundle/bundle.go, bundle/bundle_manager.go, config/config.go, go.mod, http/http.go, internal/analysis/analysis.go, internal/api/test/2024-12-21/gen.go, internal/deepcode/client.go, observability/error_reporter.go, observability/instrumentor.go, scan/tracker.go, tools.go
With the new tool approach in `go.mod`, `tools.go` was no longer needed and has been removed.
The tool will automatically download when `go tool` is used if you do not already have the version downloaded.
No more will you have to remember to `make clean` and `make install-tools`, etc. when the version of the tool changes. No more will people run with the wrong version of the tool, causing inconsistencies with mocks in the codebase because someone forgot to do this.
Now you can `go generate` a single file without having to set up your `PATH` correctly first. This means you can click the green play button in your IDE to run the generate command in the file.
For more information on `go tool` see https://tip.golang.org/doc/go1.24#tools
🚨After having merged, please update the `snyk-ls` and CLI …
=> chore: use `go tool` [IDE-1377]
